### PR TITLE
fixing rtl layout

### PR DESCRIPTION
**Pull request by ouladck**
fixing rtl layout issue:
- make Arabic/Hebrew/Persian/Urdu text right aligned
- move second nav image to the left in rtl case.

### CODE REVIEW

**Comment by pierremtb** [comment]
Thanks !

**Comment by IdrissDimson** [comment]
wait pierre revert this. It's very buggy. doesn't seem done yet.

**Comment by pierremtb** [comment]
Okay, sorry

**Comment by ouladck** [comment]
Sorry for that, but I cannot test transifex script locally, so can you tell me what is buggy in this code?

**Pull request merged**
